spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_exchange
    username: crypto_user
    password: crypto_pass

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      schema-locations: classpath:/db/ux_price_constraint.sql

  cache:
    type: caffeine
    cache-names: latest-prices
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=300s

  application:
    name: prices-module

